version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: kyc_user
      POSTGRES_PASSWORD: kyc_password
      POSTGRES_DB: kyc_prod_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    command: >
      bash -c "
      python manage.py migrate &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - DATABASE_URL=postgres://kyc_user:kyc_password@db:5432/kyc_prod_db
      - DJANGO_SECURE_SSL_REDIRECT=False
      - DJANGO_DB_SSL_REQUIRE=False
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
