# Generated by Django 6.0.4 on 2026-04-26 18:09

import django.core.validators
import kyc.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kyc", "0002_kycsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycsubmission",
            name="aadhaar_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=kyc.models.kyc_document_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    ),
                    kyc.models.validate_file_size,
                ],
            ),
        ),
        migrations.AddField(
            model_name="kycsubmission",
            name="bank_statement",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=kyc.models.kyc_document_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    ),
                    kyc.models.validate_file_size,
                ],
            ),
        ),
        migrations.AddField(
            model_name="kycsubmission",
            name="pan_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=kyc.models.kyc_document_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    ),
                    kyc.models.validate_file_size,
                ],
            ),
        ),
    ]
