# Generated by Django 6.0.4 on 2026-04-26 18:55

import django.db.models.deletion
import django.utils.timezone
import kyc.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kyc", "0003_kycsubmission_aadhaar_document_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kycsubmission",
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.AddField(
            model_name="kycsubmission",
            name="status_changed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="kycsubmission",
            name="aadhaar_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=kyc.models.kyc_document_upload_path,
                validators=[
                    kyc.models.validate_file_size,
                    kyc.models.validate_document_type,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="kycsubmission",
            name="bank_statement",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=kyc.models.kyc_document_upload_path,
                validators=[
                    kyc.models.validate_file_size,
                    kyc.models.validate_document_type,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="kycsubmission",
            name="pan_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=kyc.models.kyc_document_upload_path,
                validators=[
                    kyc.models.validate_file_size,
                    kyc.models.validate_document_type,
                ],
            ),
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="kyc.merchant",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="kyc.kycsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
