# Generated by Django 5.2.13 on 2026-04-26 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kyc", "0004_alter_kycsubmission_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NotificationLog",
            new_name="Notification",
        ),
        migrations.AlterField(
            model_name="notification",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="kyc.merchant",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="kyc.kycsubmission",
            ),
        ),
    ]
