# Generated by Django 5.2.5 on 2026-04-27 15:49

import kyc.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kyc", "0005_notification_delete_notificationlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycsubmission",
            name="aadhaar_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=kyc.models.upload_path,
                validators=[
                    kyc.models.validate_file_size,
                    kyc.models.validate_document_type,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="kycsubmission",
            name="bank_statement",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=kyc.models.upload_path,
                validators=[
                    kyc.models.validate_file_size,
                    kyc.models.validate_document_type,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="kycsubmission",
            name="pan_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=kyc.models.upload_path,
                validators=[
                    kyc.models.validate_file_size,
                    kyc.models.validate_document_type,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="phone",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="notification",
            name="payload",
            field=models.JSONField(default=dict),
        ),
    ]
