# Generated by Django 5.2.5 on 2026-04-27 16:41

import django.core.validators
import kyc.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kyc", "0006_alter_kycsubmission_aadhaar_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycsubmission",
            name="aadhaar_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=kyc.models.upload_path,
                validators=[
                    kyc.models.validate_file_size,
                    kyc.models.validate_document_type,
                    kyc.models.validate_document_signature,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="kycsubmission",
            name="bank_statement",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=kyc.models.upload_path,
                validators=[
                    kyc.models.validate_file_size,
                    kyc.models.validate_document_type,
                    kyc.models.validate_document_signature,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="kycsubmission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="kycsubmission",
            name="monthly_volume",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="kycsubmission",
            name="pan_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=kyc.models.upload_path,
                validators=[
                    kyc.models.validate_file_size,
                    kyc.models.validate_document_type,
                    kyc.models.validate_document_signature,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="kycsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("more_info_requested", "More Info Requested"),
                ],
                db_index=True,
                default="draft",
                max_length=30,
            ),
        ),
    ]
